# -------------------------------------------------------
# Development Docker Image
#
# Used only for local development.
# Runs the Vite development server with
# Hot Module Replacement (HMR).
# -------------------------------------------------------

# Base Image
FROM node:20-alpine

# Set working directory inside the container
WORKDIR /app

# Copy dependency files
COPY package*.json ./

# Install project dependencies
RUN npm install

# Copy application source code
COPY . .

# Expose Vite development server port
EXPOSE 5173

# Start Vite Development Server
CMD ["npm", "run", "dev", "--", "--host"]